return {
  "catppuccin/nvim",
  name = "catppuccin",
  opts = {
    show_end_of_buffer = true,
    flavour = "mocha", -- latte, frappe, macchiato, mocha
    background = { -- :h background
      light = "latte",
      dark = "mocha",
    },
    term_colors = true,
    dim_inactive = {
      enabled = false,
      shade = "dark",
      percentage = 0.25,
    },
    styles = {
      comments = { "italic" },
      conditionals = { "italic" },
      loops = {},
      functions = {},
      keywords = {},
      strings = {},
      variables = {},
      numbers = {},
      booleans = {},
      properties = {},
      types = {},
      operators = {},
    },
    color_overrides = {},
    custom_highlights = {},
    integrations = {
      aerial = true,
      alpha = true,
      gitsigns = true,
      indent_blankline = {
        enabled = true,
        colored_indent_levels = true,
      },
      leap = true,
      markdown = true,
      mason = true,
      mini = true,
      neotree = true,
      noice = true,
      cmp = true,
      dap = { enabled = true, enable_ui = true },
      native_lsp = {
        enabled = true,
        inlay_hints = {
          background = true,
        },
        virtual_text = {
          errors = { "italic" },
          hints = { "italic" },
          warnings = { "italic" },
          information = { "italic" },
        },
        underlines = {
          errors = { "underline" },
          hints = { "underline" },
          warnings = { "underline" },
          information = { "underline" },
        },
      },
      notify = true,
      semantic_tokens = true,
      treesitter_context = true,
      treesitter = true,
      nvimtree = false,
      ts_rainbow = true,
      ts_rainbow2 = true,
      symbols_outline = true,
      telescope = true,
      lsp_trouble = true,
      which_key = true,
      headlines = true,
      sandwich = true,
    },
  },
}

-- return {
--   "catppuccin/nvim",
--   name = "catppuccin",
--   opts = {
--     dim_inactive = { enabled = true, percentage = 0.25 },
--     integrations = {
--       alpha = false,
--       dashboard = false,
--       flash = false,
--       nvimtree = false,
--       ts_rainbow = false,
--       ts_rainbow2 = false,
--       barbecue = false,
--       indent_blankline = false,
--       navic = false,
--       dropbar = false,
--
--       aerial = true,
--       dap = { enabled = true, enable_ui = true },
--       headlines = true,
--       mason = true,
--       native_lsp = { enabled = true, inlay_hints = { background = false } },
--       neogit = true,
--       neotree = true,
--       noice = true,
--       notify = true,
--       sandwich = true,
--       semantic_tokens = true,
--       symbols_outline = true,
--       telescope = { enabled = true },
--       which_key = true,
--     },
--     custom_highlights = {
--       -- disable italics  for treesitter highlights
--       TabLineFill = { link = "StatusLine" },
--       LspInlayHint = { style = { "italic" } },
--       ["@parameter"] = { style = {} },
--       ["@type.builtin"] = { style = {} },
--       ["@namespace"] = { style = {} },
--       ["@text.uri"] = { style = { "underline" } },
--       ["@tag.attribute"] = { style = {} },
--       ["@tag.attribute.tsx"] = { style = {} },
--     },
--   },
-- }
